### ISSUE TITLE
module transpilation chops off a character in `var` and stops the app from booting

### ISSUE THREAD

**Issue by saarangsoltani** [ember-cli/ember-export-application-global#11] opened 2015-05-03 02:22 UTC
There is this  annoying bug thats stopping the app from booting. somehow `var` turns to `ar` after compilation :

![screenshot](http://i.imgur.com/ntITc5R.png)

**Comment by Patrickmnts** [comment] 2015-05-04 23:15
Running into the same issue after an upgrade.  It appears to be due to an issue within the compilation to ES5.  Possibly related to the deprecation notices seen for ember-cli-6to5??

**Comment by rwjblue** [comment] 2015-05-04 23:18
Something is wrong with module transpilation that is chopping off a character.  Can you let us know what version of the ember-cli you are using, and if you have ember-cli-babel, ember-cli-6to5, or ember-cli-esnext?

**Comment by Patrickmnts** [comment] 2015-05-04 23:39
@rwjblue of course.  Currently we are running EmberCLI 0.1.5 / Ember 1.10.0

I removed ember-cli-esnext and replaced it with ember-cli-babel recently upon seeing the deprecation notices. 

```
//package.json
{
  "name": "frontend",
  "version": "0.0.0",
  "description": "Small description",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-sass": "^0.4.0",
    "connect-restreamer": "^1.0.1",
    "ember-cli": "0.1.5",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-bootstrap-sassy": "0.0.12",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-datepicker": "^2.0.1",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-document-title": "0.0.3",
    "ember-cli-es5-shim": "^0.1.0",
    "ember-cli-htmlbars": "^0.7.4",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-moment": "0.0.1",
    "ember-cli-nouislider": "^0.2.0",
    "ember-cli-qunit": "0.1.2",
    "ember-cli-sass": "^3.1.0",
    "ember-cli-simple-auth": "^0.7.3",
    "ember-cli-simple-auth-oauth2": "^0.7.3",
    "ember-cli-simple-auth-testing": "^0.7.3",
    "ember-cli-simple-auth-token": "^0.5.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-export-application-global": "^1.0.0",
    "ember-flash-messages": "^0.5.2",
    "ember-moment": "^1.1.1",
    "ember-radio-button": "^1.0.1",
    "ember-truth-helpers": "0.0.5",
    "ember-waypoints": "0.0.5",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "liquid-fire": "^0.17.0",
    "morgan": "^1.5.1",
    "rimraf": "2.2.8"
  }
}
```

```
//bower.json
{
  "name": "web-app-frontend",
  "dependencies": {
    "jquery": "^1.11.1",
    "ember": "1.10.0",
    "ember-data": "1.0.0-beta.14.1",
    "ember-resolver": "~0.1.11",
    "loader.js": "stefanpenner/loader.js#1.0.1",
    "ember-cli-shims": "stefanpenner/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "stefanpenner/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "ember-simple-auth": "0.7.3",
    "moment": "~2.9.0",
    "pikaday": "~1.3.2",
    "bootstrap-sass-official": "~3.3.3",
    "ember-cli-moment-shim": "~0.0.3",
    "es5-shim": "^4.0.5",
    "jquery-cookie": "~1.4.1",
    "nouislider": "~7.0.10"
  }
}
```

**Comment by saarangsoltani** [comment] 2015-05-06 00:38
Here are my settings
```javascript
{
   "ember-cli": "0.1.5",
   "ember-cli-esnext": "0.1.1",
}
```
But like @Patrickmnts said, this happened after upgrading. In my case it crept up after upgrading my ember-cli-selectize package that apparently depends on ember-cli-babel :
![screenshot](http://i.imgur.com/jscNE4P.png)

**Comment by saarangsoltani** [comment] 2015-05-13 00:35
Do we have any workaround for this?

**Comment by rwjblue** [comment] 2015-05-13 00:37
It is only happening in a small number of scenarios, and I cannot reproduce. My suggestion is to upgrade to the latest version of ember-cli-babel and ember-cli.

**Comment by dmuneras** [comment] 2015-05-21 21:06
+1

**Comment by stefanpenner** [comment] 2015-07-20 23:45
Unfortunately without a reproduction this isn't actionable. It appears to be working fine on relatively new versions of ember-cli.

Im going to close this, but will reopen if a repro or further information (on a recent version of cli) is made available.

**Closed by stefanpenner** 2015-07-20 23:45 UTC
